// export const violations = [
//   {
//     id: 1,
//     title: 'اجمالي عدد حملة الوثائق',
//     number: 1200,
//     recommendation: 'مدير الاستثمار',
//     action: '22 فبراير 2022',
//   },
//   {
//     id: 2,
//     title: 'نسب استثمار الجهة المؤسسة',
//     number: 1200,
//     recommendation: 'اغلاق المخالفة',
//     action: 'اغلاق المخالفة',
//   },
//   {
//     id: 3,
//     title: 'اذون خزانة البنك المركزي المصري',
//     number: 1200,
//     recommendation: 'اغلاق المخالفة',
//     action: 'اغلاق المخالفة',
//   },
//   {
//     id: 4,
//     title: 'سندات قابلة للتحويل النقدي',
//     number: 1200,
//     recommendation: 'اغلاق المخالفة',
//     action: 'اغلاق المخالفة',
//   },
// ]

export const violations = [
  {
    id: 1,
    fundName: 'صندوق نماء',
    class: 'one',
    violations: [
      {
        id: 1,
        title: 'اجمالي عدد حملة الوثائق',
        number: 1200,
        recommendation: 'مدير الاستثمار',
        action: '22 فبراير 2022',
      },
      {
        id: 2,
        title: 'نسب استثمار الجهة المؤسسة',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'اذون خزانة البنك المركزي المصري',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 4,
        title: 'سندات قابلة للتحويل النقدي',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 2,
    fundName: 'صندوق ثراء',
    class: 'two',
    violations: [
      {
        id: 1,
        title: 'اجمالي عدد حملة الوثائق',
        number: 1200,
        recommendation: 'مدير الاستثمار',
        action: '22 فبراير 2022',
      },
      {
        id: 2,
        title: 'نسب استثمار الجهة المؤسسة',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'اذون خزانة البنك المركزي المصري',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 4,
        title: 'سندات قابلة للتحويل النقدي',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 3,
    fundName: 'صندوق الخير',
    class: 'three',
    violations: [
      {
        id: 1,
        title: 'اجمالي عدد حملة الوثائق',
        number: 1200,
        recommendation: 'مدير الاستثمار',
        action: '22 فبراير 2022',
      },
      {
        id: 2,
        title: 'نسب استثمار الجهة المؤسسة',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'اذون خزانة البنك المركزي المصري',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 4,
        title: 'سندات قابلة للتحويل النقدي',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 4,
    fundName: 'صندوق الحكمة',
    class: 'four',
    violations: [
      {
        id: 1,
        title: 'اجمالي عدد حملة الوثائق',
        number: 1200,
        recommendation: 'مدير الاستثمار',
        action: '22 فبراير 2022',
      },
      {
        id: 2,
        title: 'نسب استثمار الجهة المؤسسة',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'اذون خزانة البنك المركزي المصري',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 4,
        title: 'سندات قابلة للتحويل النقدي',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 5,
    fundName: 'صندوق سندى',
    class: 'five',
    violations: [
      {
        id: 1,
        title: 'اجمالي عدد حملة الوثائق',
        number: 1200,
        recommendation: 'مدير الاستثمار',
        action: '22 فبراير 2022',
      },
      {
        id: 2,
        title: 'نسب استثمار الجهة المؤسسة',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'اذون خزانة البنك المركزي المصري',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
      {
        id: 4,
        title: 'سندات قابلة للتحويل النقدي',
        number: 1200,
        recommendation: 'اغلاق المخالفة',
        action: 'اغلاق المخالفة',
      },
    ],
  },
]