export const violations = [
  {
    id: 1,
    companyName: 'شركة الأهلي',
    class: 'one',
    violations: [
      {
        id: 1,
        title: 'صندوق إستثمار بنك عودة المتوازن',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 2,
        title: 'صندوق الأهلي التجاري',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'صندوق السويس التجاري ',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 2,
    companyName: 'شركة العرب المستثمرون',
    class: 'two',
    violations: [
      {
        id: 1,
        title: 'صندوق إستثمار بنك عودة المتوازن',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 2,
        title: 'صندوق الأهلي التجاري',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'صندوق السويس التجاري ',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 2,
    companyName: 'شركة الرواد',
    class: 'one',
    violations: [
      {
        id: 1,
        title: 'صندوق إستثمار بنك عودة المتوازن',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 2,
        title: 'صندوق الأهلي التجاري',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'صندوق السويس التجاري ',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
    ],
  },
  {
    id: 4,
    companyName: 'شركة الوسام',
    class: 'two',
    violations: [
      {
        id: 1,
        title: 'صندوق إستثمار بنك عودة المتوازن',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 2,
        title: 'صندوق الأهلي التجاري',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
      {
        id: 3,
        title: 'صندوق السويس التجاري ',
        fundNo: 32321,
        late: 12,
        recommendation: 'اغلاق المخالفة',
        decision: 'اغلاق المخالفة',
      },
    ],
  },
]